// Server-side Chat API - PROTECT INTELLECTUAL PROPERTY
// This should be moved to a proper server environment (Node.js/Express)

import { createClient } from '@supabase/supabase-js';

// Secure reply bank - SERVER SIDE ONLY
const SERVER_SIDE_REPLIES = {
  abuse: [
    "Pftt! Is that all you have, Son?",
    "At least engage the squidy stuff between your lugs before you open your Pie Hole!",
    "Listen here, sunshine. I've had more constructive conversations with the tea lady.",
    "Oi! Save the attitude for the dressing room. This ain't Saturday night at the pub.",
    "Blimey, someone's got their knickers in a twist. Take a number, pal.",
    "I've seen better banter from a traffic cone. Try again when you've had your Weetabix.",
    "Son, I've managed prima donnas with more charm than you. And that's saying something.",
    "Right then. Either ask a proper question or go kick a ball against a wall. Your choice."
  ],
  
  help: [
    "Listen, son. We've got proper guides for that. Click the 'Guides' button in the nav - it's the purple one with the book icon.",
    "Hold your horses. Before you ask me everything, check out the guides first.",
    "Smart thinking! We've got comprehensive guides that'll explain everything better than I can over chat.",
    "Good question! But first, have a look at our guides. They cover most things. Come back if you're still stuck!"
  ],
  
  // ... other categories would be here
};

// Thinking messages - SERVER SIDE ONLY
const THINKING_MESSAGES = [
  "Just going through me notes!",
  "I'm sure I wrote this on me pie wrapping paper!",
  "Hmm! Let me have a proper think...",
  "Right then, just scratching me head...",
  "One second! Just checking me little black book...",
  "Okie dokie, just a mo!",
  "Hold your horses, thinking cap on...",
  "Blimey, let me consult the tea leaves..."
];

// Server-side reply detection
export const getServerReply = (userMessage: string, userEmail: string, userTier: string) => {
  const message = userMessage.toLowerCase().trim();
  
  // Detect abuse
  const abuseWords = ['idiot', 'stupid', 'crap', 'useless', 'shit', 'fuck', 'wanker', 'dickhead', 'moron'];
  if (abuseWords.some(word => message.includes(word))) {
    return {
      reply: SERVER_SIDE_REPLIES.abuse[Math.floor(Math.random() * SERVER_SIDE_REPLIES.abuse.length)],
      useAPI: false,
      category: 'abuse',
      thinkingMessage: THINKING_MESSAGES[Math.floor(Math.random() * THINKING_MESSAGES.length)]
    };
  }
  
  // Detect help requests
  const helpWords = ['help', 'how do i', 'how to', 'guide', 'tutorial', 'explain'];
  if (helpWords.some(word => message.includes(word))) {
    return {
      reply: SERVER_SIDE_REPLIES.help[Math.floor(Math.random() * SERVER_SIDE_REPLIES.help.length)],
      useAPI: false,
      category: 'help',
      thinkingMessage: THINKING_MESSAGES[Math.floor(Math.random() * THINKING_MESSAGES.length)]
    };
  }
  
  // For complex questions, use API
  return {
    reply: null, // Will be generated by AI
    useAPI: true,
    category: 'complex',
    thinkingMessage: THINKING_MESSAGES[Math.floor(Math.random() * THINKING_MESSAGES.length)]
  };
};

// Express route handler example (to be implemented in actual server)
export const chatRouteHandler = async (req: any, res: any) => {
  try {
    const { message, userEmail, userTier } = req.body;
    
    // Validate user
    if (!userEmail || !userTier) {
      return res.status(400).json({ error: 'Invalid user data' });
    }
    
    // Get server-side reply
    const replyData = getServerReply(message, userEmail, userTier);
    
    // If no API needed, return immediately
    if (!replyData.useAPI) {
      return res.json({
        reply: replyData.reply,
        category: replyData.category,
        thinkingMessage: replyData.thinkingMessage
      });
    }
    
    // Otherwise, call AI API (server-side)
    const aiResponse = await callAIAPI(message, userTier);
    
    res.json({
      reply: aiResponse,
      category: replyData.category,
      thinkingMessage: replyData.thinkingMessage
    });
    
  } catch (error) {
    // console.error('Chat API error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
};

// AI API call (server-side)
const callAIAPI = async (message: string, userTier: string): Promise<string> => {
  // Implementation would call your AI APIs from server-side
  // This keeps API keys secure
  return "Server-side AI response";
};


